baseURL = 'https://inkandbits.github.io/'
languageCode = 'en-us'
title = 'Ode: An Ode to Lost Knowledge.'
theme = 'clean-white'

preserveTaxonomyNames = true
pagination.pagerSize = 5 #frontpage pagination
hasCJKLanguage = true



[outputs]
home = ["HTML", "RSS"]


[params]
  header_image = "img/post-bg-coffee.jpeg"
  SEOTitle = "Ode"
  description = "A Blog written by some people."
  slogan = "An Ode to Knowledge."
  upstreamAttribution = true

  image_404 = "img/404-bg.jpg"
  title_404 = "Sorry, there seems to be an error :("
  omit_categories = false




  # Sidebar settings
  sidebar_about_description = "Bringin you the best articles."


   featured_tags = true
  featured_condition_size = 1



[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"
